function result = guass_int_error_1d (exact_solution_fun, gauss_weights, gauss_points, uh_local, vertices, basis_type, der)
result = sum(gauss_weights .* ...
            (feval(exact_solution_fun, gauss_points)...
             - FE_function_1d(gauss_points, uh_local, vertices, basis_type, der)) .^ 2);
end
